# Generated by Django 5.1.7 on 2025-04-27 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='department',
            table=None,
        ),
        migrations.AlterModelTable(
            name='petition',
            table=None,
        ),
        migrations.AlterModelTable(
            name='profile',
            table=None,
        ),
    ]
