# Generated by Django 5.1.7 on 2025-05-10 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_department_table_alter_petition_table_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='petition',
            old_name='created_at',
            new_name='date_submitted',
        ),
        migrations.RemoveField(
            model_name='petition',
            name='is_spam',
        ),
        migrations.RemoveField(
            model_name='petition',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='petition',
            name='sentiment',
        ),
        migrations.RemoveField(
            model_name='petition',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='department',
            name='officer',
            field=models.OneToOneField(blank=True, limit_choices_to={'profile__role': 'officer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='petition',
            name='date_resolved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='petition',
            name='proof_file',
            field=models.FileField(blank=True, null=True, upload_to='proofs/'),
        ),
        migrations.CreateModel(
            name='AIAnalysedPetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10)),
                ('sentiment', models.CharField(choices=[('Positive', 'Positive'), ('Neutral', 'Neutral'), ('Negative', 'Negative')], max_length=10)),
                ('is_spam', models.BooleanField(default=False)),
                ('petition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apps.petition')),
            ],
        ),
    ]
