# Generated by Django 5.1.7 on 2025-05-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_remove_department_officer_department_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='image',
        ),
        migrations.AddField(
            model_name='department',
            name='image_url',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
