# Generated by Django 5.1.7 on 2025-05-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_remove_department_image_department_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
