# Generated by Django 5.1.7 on 2025-05-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_alter_department_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='address',
            field=models.TextField(default='address'),
        ),
        migrations.AddField(
            model_name='petition',
            name='incident_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='petition',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AddField(
            model_name='petition',
            name='pincode',
            field=models.CharField(default='000000', max_length=6),
        ),
        migrations.AlterField(
            model_name='petition',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='Pending', max_length=20),
        ),
    ]
