# Generated by Django 5.1.7 on 2025-05-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_alter_officerprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
